version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 60 --cleanup

  caddy:
    image: iarekylew00t/caddy-cloudflare:latest
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/caddy/Caddyfile:/etc/caddy/Caddyfile
      # - ./data/caddy/caddy_data:/data
      # - ./data/caddy/caddy_config:/config
      - ./data/personal-site/var/www:/var/www/licu.dev:ro

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./data/mongo/db:/data/db

  personal-site:
    image: ghcr.io/lmihaig/personal-site:latest
    volumes:
      - ./data/personal-site/var/www:/var/www/licu.dev

  spirit-of-anton:
    image: ghcr.io/lmihaig/spirit-of-anton:latest
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DB_URI=${DB_URI}
